### ISSUE TITLE
您好，读取你的雷达数据没问题，但是用我自己的雷达数据时报错，麻烦看看

### ISSUE THREAD

**Issue by zhouaming9** [bugsuse/mradar#3]
您好，感谢您提供雷达基数据的读取程序，我下载使用了，读取你的雷达数据（SA_CAP.bin）没问题，但是用我自己的雷达基数据（Z_RADR_I_Z9200_20170822180000_O_DOR_SA_CAP.bin）时出错（报错信息如下：
错误使用  * 
内部矩阵维度必须一致。

出错 read_sradar>get_data (line 114)
    r = ((1:dnum) - 0.5)*distance;

出错 read_sradar>get_prod (line 135)
    [prod, lat, lon, height, llunits, azimuths, elevations] = get_data(data, eleidse, ray_nums, distance, start, longitude, latitude);

出错 read_sradar (line 97)
    radar = get_prod(radar, data, i, types, eleidse, eleva, longitude, latitude);

出错 test (line 17)
radar = read_sradar(filename, types, lon, lat, 179);）。
我和你的数据格式应该是一样的，麻烦看看。谢谢。

**Comment by bugsuse** [comment]
https://github.com/bugsuse/mradar/blob/65e1ec085c4c0af60b40ba674d110e68a679e812/io/read_sradar.m#L132-L133
这是一个bug，一开始的时候只是想处理单层的数据，一般不会出现这种问题，如果要同时处理多层的时候，尤其是出现多个相同仰角扫描时就会出现此类问题。暂时解决了处理反射率的问题，径向速度的读取没什么问题，但还有待做进一步检查。后面会对这部分程序进行重构。

如果你对python熟悉的话，可以看一下https://github.com/bugsuse/pyart，我把处理S波段的接口整合到这个库里了，没有这个问题，目前也比较稳定。
