### ISSUE TITLE
没有考虑等效地球半径

### ISSUE THREAD

**Issue by daxinnan** [bugsuse/mradar#4]
个人认为，
1计算仰角高度的时候没有考虑大气折射问题，所以求解相对高度不能直接sph2cart直接求解。[测高公式](http://courses.lzu.edu.cn/courses/112112/html/kcxx/05/01.html)
2，然后我想再问一下画出来的图上点一下不是有x,y,z嘛，z为啥全是0。
![image](https://user-images.githubusercontent.com/26436171/64595118-e389b300-d3e3-11e9-8d81-e6042bbe067d.png)
谢谢

**Comment by bugsuse** [comment]
@daxinnan 感谢提出此问题！PS：很久没用matlab了，所以一直耽搁了忘了修复=_=
1. 最新的更新修复了此问题。可以下载测试。
2. pcolor画的图只用了x和y，没有用到z，所以z全都是0。
